---
  - hosts: all
    become: yes
    pre_tasks:
      - name: Instala git
        apt:
          pkg: git
          state: present

      - name: Instalando herramientas necesarias
        sudo: yes
        apt:
          pkg: [wget,curl,python-minimal,python-setuptools,python-pip,python3-pip]
          state: present

    tasks:
      - name: Clonando repositorio github
        become: false
        git:
          repo: 'https://github.com/AlejandroCN7/Proyecto-Cloud-Computing.git'
          clone: yes
          dest: ~/proyecto

      - name: Instalando dependencias del proyecto
        become: false
        pip:
          requirements: ~/proyecto/requirements.txt
          executable: pip3


      - name: Redirigiendo puertos
        become: true
        lineinfile:
          path: /etc/rc.local
          insertbefore: 'exit 0'
          line: "sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 5000"
